package com.yaohun.demonskills.event;

import com.yaohun.demonskills.core.Skill;
import org.bukkit.entity.Player;
import org.bukkit.event.Event;
import org.bukkit.event.HandlerList;

public class SkillCastEvent extends Event {

    private static HandlerList handlers = new HandlerList();

    public HandlerList getHandlers() {
        return handlers;
    }

    public static HandlerList getHandlerList() {
        return handlers;
    }

    private Player player;
    private Skill skill;

    public SkillCastEvent(Player player, Skill skill) {
        this.player = player;
        this.skill = skill;
    }

    public Player getPlayer() {
        return player;
    }

    public Skill getSkill() {
        return skill;
    }
}
